<?php 
	$_code=$this->getMethodCode();
	$publickey=Mage::getStoreConfig('payment/tarjeta/apikey');
	include_once(dirname(__FILE__) . '/../../payment_logic.phtml');
?>

<ul style="display:none;" id="payment_form_<?php echo $_code ?>" class="form-list">
	<li>
		<label class="oxxo-errors" style="color:red;"></label>
	</li>
	<li>
		<input type="hidden" value="" name="payment[codigo_barras]" id="codigo_barras" class="input-text" title="Codigo Barras" autocomplete="off">
	</li>
	<li>
		<input type="hidden" value="" name="payment[codigo]" id="codigo" class="input-text" title="Codigo" autocomplete="off">
	</li>
	<li>
		<input type="hidden" value="" name="payment[referencia]" id="referencia" class="input-text" title="Referencia" autocomplete="off">
	</li>
</ul>

<div>
	<?php echo $this->getMethod()->getConfigData('message');?>
</div>
