<?php
	$method = Mage::getSingleton('checkout/session')->getQuote()->getPayment()->getData('method');
	$quoteid = Mage::getSingleton('checkout/session')->getQuote()->getId();
	$quote= Mage::getModel('sales/quote_payment')->load($quoteid);
	$totals = Mage::getSingleton('checkout/session')->getQuote()->getTotals();
	$grandtotal = round($totals["grand_total"]->getValue());
?>
<style type="text/css">
	@import url(http://fonts.googleapis.com/css?family=Source+Code+Pro);
	.ckta::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .col-1 { float: left;width: 452px; }
	.ckta .col-2 { float: right;width: 152px; }
	.ckta h3 { height: 24px;border-bottom: 1px solid #e4e4e4;padding-bottom: 2px; }
	.ckta .fade { -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";filter: alpha(opacity=50);-moz-opacity: 0.5;-khtml-opacity: 0.5;opacity: 0.5; }
	.ckta .ficha { position: relative;padding: 10px 0;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;margin: 2px 0 6px 0;border: 1px solid #B6B6B6;background: white; }
	.ckta .ficha::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .ficha  h3 { display: none;font-size: 16px;padding: 0;border: none;margin-left: 16px; }
	.ckta .ficha p::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .ficha dl { margin-left: 16px; }
	.ckta .barcode p span:first-child { float: left; }
	.ckta .barcode p span:last-child { float: right; }
	.ckta .button { display: block; }
	.ckta.ficha-oxxo h4 { margin-top: 77px; }
	.ckta.ficha-oxxo .ficha p { font-family: 'Source Code Pro', sans-serif;font-size: 12px;margin: 1px 15px 0 16px; }
	.ckta.ficha-banco h4 { margin-top: 59px;}
	.ckta.ficha-banco .ficha p { }
	.ckta.ficha-banco .ficha .dl-box { width: 200px; }
	.ckta.ficha-banco .ficha dl dt { float: left;width: 110px;font-weight: bold; }
	.ckta.ficha-banco .ficha dl dd { float: left; }
	.ckta.ficha-banco .ficha .ammount { position: absolute;top: 10px;right: 15px; }
</style>
<form id="co-invoice-form" action="">
	<fieldset>
		<ul class="form-list">
<?php if(strcmp($method, 'oxxo') == 0) : ?>
	<li class="ckta ficha-oxxo" id="checkout-invoice-load">													
		<div class="col-1">
			<h3>Ficha de Pago para OXXO</h3>
			<p>Utiliza esta ficha para realizar el pago en la tienda OXXO más cercana antes del día <strong>27/03/2014</strong>. <span class="fade">Si intentas realizar el pago después de esta necesitarás un nuevo código de barras</span>.</p>
			<div class="ficha barcode">
				<h3>Ficha de Pago para OXXO</h3>
				<?php echo "<img src='". $quote->getData('codigo_barras') ."' width='450' height='75' alt='Código de Barras para OXXO'/>" ?>
				<p><span>Monto: $ <?php echo number_format($grandtotal,2);?></span><span><?php echo $quote->getData('referencia'); ?></span></p>
			</div>
		</div>
		<div class="col-2">
			<h3></h3>
			<h4>Acciones</h4>
			<p>
				<a href="#" class="button" id="print" onclick="window.print();">Imprimir ficha</a>
			</p>
		</div>
	</li>
<?php elseif(strcmp($method, 'bank') == 0) : ?>
	<li class="ckta ficha-banco" id="checkout-invoice-load">													
		<div class="col-1">
			<h3>Ficha de Pago para Bancos</h3>
			<p>Utiliza esta ficha para realizar el pago en <strong>sucursales Banorte</strong>. <a href="http://bit.ly/SucursalesBanorte" target="_blank">Haz clic aquí</a><span class="fade"> para encontrar la sucursal Banorte más cercana.</span>
			</p>
			<div class="ficha reference">
				<h3>Ficha de Pago para Bancos</h3>
				<dl>
					<div class="dl-box">
						<dt>Banco</dt>
						<dd><?php echo ucfirst($quote->getData('bank')); ?></dd>
					</div>
					<div class="dl-box">
						<dt>Servicio</dt>
						<dd><?php echo $quote->getData('nombre_servicio'); ?></dd>
					</div>
					<div class="dl-box">
						<dt>No. de Servicio</dt>
						<dd><?php echo $quote->getData('numero_servicio'); ?></dd>
					</div>
					<div class="dl-box">
						<dt>No. de Referencia</dt>
						<dd><?php echo $quote->getData('referencia'); ?></dd>
					</div>
				</dl>
				<p class="ammount"><strong>$ <?php echo number_format($grandtotal,2);?></strong></p>
			</div>
		</div>
		<div class="col-2">
			<h3></h3>
			<h4>Acciones</h4>
			<p>
				<a href="#" class="button" id="print" onclick="window.print();">Imprimir ficha</a>
			</p>
		</div>
	</li>
<?php else : ?>
	<li class="ckta ficha-tarjeta" id="checkout-invoice-load">													
		<div class="col-1">
			<p>Este método de compra no tiene invoice de pago. Da clic en continuar.<p>
		</div>
		<div class="col-2">
			
		</div>
	</li>
<?php endif; ?>
		</ul>		
	</fieldset>
</form>
