<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="https://conektaapi.s3.amazonaws.com/v0.3.0/js/conekta.js"></script>
<script type="text/javascript">
  $.noConflict();
	jQuery(function($) {
		Conekta.setPublishableKey("<?php echo $publickey ?>");
		var conektaSuccessResponseHandler = function(response) {
			var $form = $("#payment_form_tarjeta");
			var token_id = response.id;
			$form.find('#tarjeta_cc_tokenid').val(token_id);
			$form.find('.card-errors').text("");
			payment.save();
		};
		var conektaErrorResponseHandler = function(response) {
			var $form = $("#payment_form_tarjeta");
			$form.find('.card-errors').text(response.message);
		};
		
		$('#payment-buttons-container .button').unbind('click');
		$('#payment-buttons-container .button').attr('onclick','');
		$('#payment-buttons-container .button').click(function() {
			if ($("#p_method_tarjeta").prop('checked')) {
				var $form = $("#payment_form_tarjeta");
				$form.find('#tarjeta_cc_nombre').val($("#tarjeta_cc_owner").val());
				$form.find('#tarjeta_cc_numero').val($("#tarjeta_cc_number").val());
				$form.find('#tarjeta_cc_mes').val($("#tarjeta_expiration").val());
				$form.find('#tarjeta_cc_anio').val($("#tarjeta_expiration_yr").val());
				Conekta.token.create($form, conektaSuccessResponseHandler, conektaErrorResponseHandler);
			} else if ($("#p_method_oxxo").prop('checked')) {
				$.ajax({
					type: "POST",
					url: "<?php echo $this->getUrl('oxxo/ajax', array('_secure'=>true)); ?>",
					dataType: "text",
					data: "",
					async: false,
					success: function (data) {
						var $form = $("#payment_form_oxxo");
						data = $.parseJSON(data);
						if (data.error) {
							$form.find('.oxxo-errors').text(data.error);
						} else if (data.barcode) {
							$form.find('.oxxo-errors').text("");
							$form.find('#codigo_barras').val(data.barcode);
							payment.save();
						} else {
							$form.find('.oxxo-errors').text("Método de pago no disponible, intente más tarde.");
						}
					},
					error: function (textStatus, errorThrown) {
						var $form = $("#payment_form_oxxo");
						$form.find('.oxxo-errors').text("Método de pago no disponible, intente más tarde.");
					}
				});
      } else if ($("#p_method_banco").prop('checked')) {
				$.ajax({
					type: "POST",
					url: "<?php echo $this->getUrl('banco/ajax', array('_secure'=>true)); ?>",
					dataType: "text",
					data: "",
					async: false,
					success: function (data) {
						var $form = $("#payment_form_banco");
						data = $.parseJSON(data);
						if (data.error) {
							$form.find('.banco-errors').text(data.error);
						} else if (data.numero_servicio) {
							$form.find('.banco-errors').text("");
							$form.find('#numero_servicio').val(data.numero_servicio);
							$form.find('#nombre_servicio').val(data.nombre_servicio);
							$form.find('#banco').val(data.banco);
							$form.find('#referencia').val(data.referencia);
							payment.save();
						} else {
							$form.find('.banco-errors').text("Método de pago no disponible, intente más tarde.");
						}
					},
					error: function (textStatus, errorThrown) {
						var $form = $("#payment_form_banco");
						$form.find('.banco-errors').text("Método de pago no disponible, intente más tarde.");
					}
				});
			} else {
				payment.save();
			}
			return false;
		});
	});
</script>
