<?php 
	$_code=$this->getMethodCode();
	$publickey=Mage::getStoreConfig('payment/tarjeta/apikey');
	include_once(dirname(__FILE__) . '/../../payment_logic.phtml');
?>

<ul style="display:none;" id="payment_form_<?php echo $_code ?>" class="form-list">
	<li>
		<label class="oxxo-errors" style="color:red;"></label>
	</li>
	<li>
		<div class="input-box">
			<input type="hidden" value="<?php echo $barcode ?>" name="payment[codigo_barras]" id="codigo_barras" class="input-text" title="Codigo Barras" autocomplete="off">
		</div>
	</li>
</ul>

<div>
	<?php echo $this->getMethod()->getConfigData('message');?>
</div>
