<?php 
	$_code=$this->getMethodCode();
	$publickey=Mage::getStoreConfig('payment/tarjeta/apikey');
	include_once(dirname(__FILE__) . '/../../payment_logic.phtml');
?>

<ul style="display:none;" id="payment_form_<?php echo $_code ?>" class="form-list">
	<li>
		<label class="banco-errors" style="color:red;"></label>
	</li>
	<li>
		<input type="hidden" value="" name="payment[numero_servicio]" id="numero_servicio" class="input-text" title="Numero servicio" autocomplete="off">
		<input type="hidden" value="" name="payment[nombre_servicio]" id="nombre_servicio" class="input-text" title="Nombre servicio" autocomplete="off">
		<input type="hidden" value="" name="payment[banco]" id="banco" class="input-text" title="Banco" autocomplete="off">
		<input type="hidden" value="" name="payment[referencia]" id="referencia" class="input-text" title="Referencia" autocomplete="off">
	</li>
</ul>

<div>
	<?php echo $this->getMethod()->getConfigData('message');?>
</div>
