<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"><style type="text/css">
<style type="text/css">
	@import url(http://fonts.googleapis.com/css?family=Source+Code+Pro);
	.ckta::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .col-1 { float: left;width: 452px; }
	.ckta .col-2 { float: right;width: 152px; }
	.ckta h3 { height: 24px;border-bottom: 1px solid #e4e4e4;padding-bottom: 2px; }
	.ckta .fade { -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";filter: alpha(opacity=50);-moz-opacity: 0.5;-khtml-opacity: 0.5;opacity: 0.5; }
	.ckta .ficha { position: relative;padding: 10px 0;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;margin: 2px 0 6px 0;border: 1px solid #B6B6B6;background: white; }
	.ckta .ficha::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .ficha  h3 { display: none;font-size: 16px;padding: 0;border: none;margin-left: 16px; }
	.ckta .ficha p::after { content: ".";display: block; height: 0px;clear: both;visibility: hidden; }
	.ckta .ficha dl { margin-left: 16px; }
	.ckta .barcode p span:first-child { float: left; }
	.ckta .barcode p span:last-child { float: right; }
	.ckta .button { display: block; }
	.ckta.ficha-oxxo h4 { margin-top: 77px; }
	.ckta.ficha-oxxo .ficha p { font-family: 'Source Code Pro', sans-serif;font-size: 12px;margin: 1px 15px 0 16px; }
	.ckta.ficha-banco h4 { margin-top: 59px;}
	.ckta.ficha-banco .ficha p { }
	.ckta.ficha-banco .ficha .dl-box { width: 200px; }
	.ckta.ficha-banco .ficha dl dt { float: left;width: 110px;font-weight: bold; }
	.ckta.ficha-banco .ficha dl dd { float: left; }
	.ckta.ficha-banco .ficha .ammount { position: absolute;top: 10px;right: 15px; }
	.ui-dialog.success-dialog {
    font-family: Verdana,Arial,sans-serif;
    font-size: .8em;
}
</style>
  
<script type="text/javascript">
	var jqui = document.createElement('script');
	jqui.type = 'text/javascript';
	jqui.src = "//code.jquery.com/ui/1.10.4/jquery-ui.js";
	document.getElementsByTagName('head')[0].appendChild(jqui);
	var key = "<?php echo $publickey ?>";
	function printInvoice() {
		window.print();
		payment.save();
		return false;
	}	
	Conekta.setPublishableKey(key);
	var variables = document.createElement('script');
	variables.type = 'text/javascript';
	variables.innerHTML = "var conektaKey = '<?php echo $publickey ?>'; var oxxoUrl = '<?php echo $this->getUrl('oxxo/ajax', array('_secure'=>true)); ?>'; var bankUrl = '<?php echo $this->getUrl('bank/ajax', array('_secure'=>true)); ?>';";
	document.getElementsByTagName('head')[0].appendChild(variables);
	var p = document.createElement('script');
	p.type = 'text/javascript';
	p.src = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>' + '/conekta_pm_logic.js';
	document.getElementsByTagName('head')[0].appendChild(p);
</script>

